document.querySelector(".unregistered-content").remove()
document.querySelector(".registered-content").classList.remove("registered-content")
document.querySelector(".teads-inread").remove()
document.querySelector(".henneoHB-intext").remove()
document.querySelectorAll(".adimpact-3").forEach(el=>el.remove())
document.querySelectorAll(".ads-container").forEach(el=>el.remove())
